from ._1 import *
from ._2 import *
from ._3 import *
from ._4 import *
from ._5 import *
from ._6 import *
from ._7 import *
from ._8 import *
from ._9 import *
from ._10 import *
from ._11 import *
from ._12 import *
from ._13 import *
from ._14 import *
from ._15 import *
from ._16 import *
from tasks.tamagochi import tamagochi